version: '3.3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: web
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"

    networks:
      - lamp_network

networks:
  lamp_network:
